tasks:
  - init: ./gradlew clean build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - jebbs.plantuml
    - contextmapper.context-mapper-vscode-extension
    - vscjava.vscode-java-pack
    - asciidoctor.asciidoctor-vscode
