tasks:
  - init: ./gradlew clean build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - jebbs.plantuml@2.13.12:LcphKtCbPTIScvq6ELiS8Q==
    - contextmapper.context-mapper-vscode-extension@5.15.0:YC+du3ZmHAPRfQz6cV2BBA==