tasks:
  - init: ./gradlew clean build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - contextmapper.context-mapper-vscode-extension@5.13.0:gvdR0EGzTImP4QJvjK06ug==
    - jebbs.plantuml@2.13.12:LcphKtCbPTIScvq6ELiS8Q==